#!/usr/bin/env python3
"""Zephyr workspace manager — app/board selection, build, and flash."""
import argparse
import json
import os
import subprocess
import sys

WORKSPACE = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
CONFIG_FILE = os.path.join(WORKSPACE, '.vscode', 'zephyr-config.json')
ACTIVE_FILE = os.path.join(WORKSPACE, '.vscode', '.active-config.json')
ACTIVE_OCD_CFG = os.path.join(WORKSPACE, '.vscode', 'openocd', 'active.cfg')
ACTIVE_SVD     = os.path.join(WORKSPACE, '.vscode', 'svd', 'active.svd')
DEBUG_BUILD_DIR = os.path.join(WORKSPACE, 'build', 'debug')


def load_config():
    if not os.path.exists(CONFIG_FILE):
        print(f"ERROR: Config file not found: {CONFIG_FILE}")
        sys.exit(1)
    with open(CONFIG_FILE) as f:
        return json.load(f)


def load_active():
    if not os.path.exists(ACTIVE_FILE):
        print("ERROR: No active configuration. Run 'Zephyr: Select App & Board' first.")
        sys.exit(1)
    with open(ACTIVE_FILE) as f:
        return json.load(f)


def select_from_list(items, prompt, name_key='name', detail_key=None):
    """Show a numbered menu and return the chosen item."""
    print(f"\n{prompt}")
    print("-" * 50)
    for i, item in enumerate(items, 1):
        detail = f"  [{item[detail_key]}]" if detail_key and detail_key in item else ""
        desc = f"  — {item['description']}" if 'description' in item else ""
        print(f"  {i:2d}.  {item[name_key]}{detail}{desc}")
    print()
    while True:
        try:
            line = input(f"Enter number (1–{len(items)}): ").strip()
            idx = int(line) - 1
            if 0 <= idx < len(items):
                return items[idx]
        except (ValueError,):
            pass
        except (KeyboardInterrupt, EOFError):
            print("\nCancelled.")
            sys.exit(0)
        print(f"  Please enter a number between 1 and {len(items)}.")


def cmd_select(_args):
    """Interactively select app and board, update active config."""
    config = load_config()

    apps = config.get('applications', [])
    boards = config.get('boards', [])

    if not apps:
        print("No applications in .vscode/zephyr-config.json — add one first.")
        sys.exit(1)
    if not boards:
        print("No boards in .vscode/zephyr-config.json — add one first.")
        sys.exit(1)

    print("\n╔══════════════════════════════════════╗")
    print("║    Zephyr Configuration Selector     ║")
    print("╚══════════════════════════════════════╝")

    app = select_from_list(apps, "Select Application:", 'name')
    board = select_from_list(boards, "Select Board:", 'name', 'id')

    svd_rel = board.get('svd_file', '')
    svd_abs = os.path.join(WORKSPACE, svd_rel) if svd_rel else ''

    active = {
        'app_name': app['name'],
        'app_path': app['path'],
        'board_id': board['id'],
        'board_name': board['name'],
        'openocd_cfg': board.get('openocd_cfg', ''),
        'gdb_target': board.get('gdb_target', ''),
        'svd_file': svd_rel,
        'board_root': board.get('board_root', ''),
        'build_dir': 'build/debug',
    }

    # Write active config
    with open(ACTIVE_FILE, 'w') as f:
        json.dump(active, f, indent=2)

    # Write active.cfg that sources the board's OpenOCD config
    board_cfg_path = os.path.join(WORKSPACE, active['openocd_cfg'])
    os.makedirs(os.path.dirname(ACTIVE_OCD_CFG), exist_ok=True)
    with open(ACTIVE_OCD_CFG, 'w') as f:
        f.write(f"# Auto-generated by zephyr.py — do not edit manually.\n")
        f.write(f"# Board: {board['name']} ({board['id']})\n")
        f.write(f"source \"{board_cfg_path}\"\n")

    # Copy SVD so launch.json can always reference a fixed path
    import shutil
    os.makedirs(os.path.dirname(ACTIVE_SVD), exist_ok=True)
    if svd_abs and os.path.exists(svd_abs):
        shutil.copy2(svd_abs, ACTIVE_SVD)
        svd_status = os.path.basename(svd_abs)
    elif svd_abs:
        # Create a placeholder so VS Code doesn't error on a missing file
        open(ACTIVE_SVD, 'w').close()
        svd_status = f"MISSING — place {os.path.basename(svd_abs)} in .vscode/svd/"
    else:
        open(ACTIVE_SVD, 'w').close()
        svd_status = "none configured"

    print(f"\n{'='*50}")
    print(f"  Application : {app['name']}")
    print(f"  Path        : {app['path']}")
    print(f"  Board       : {board['name']}")
    print(f"  Board ID    : {board['id']}")
    print(f"  Build dir   : build/debug")
    print(f"  SVD         : {svd_status}")
    print(f"{'='*50}")
    print("\nDone. Use 'Zephyr: Build' to compile.")


def cmd_build(args):
    """Build the active Zephyr application with west."""
    active = load_active()
    app_abs = os.path.join(WORKSPACE, active['app_path'])
    board_id = active['board_id']

    print(f"\n  App   : {active['app_name']}")
    print(f"  Board : {active['board_name']} ({board_id})")
    print(f"  Dir   : {DEBUG_BUILD_DIR}")
    print()

    cmd = [
        'west', 'build',
        '-b', board_id,
        app_abs,
        '--build-dir', DEBUG_BUILD_DIR,
    ]
    if args.pristine:
        cmd.append('--pristine')

    # Pass BOARD_ROOT for custom boards outside the Zephyr tree
    board_root = active.get('board_root', '')
    if board_root:
        board_root_abs = os.path.join(WORKSPACE, board_root)
        cmd.extend(['--', f'-DBOARD_ROOT={board_root_abs}'])

    result = subprocess.run(cmd, cwd=WORKSPACE)
    sys.exit(result.returncode)


def cmd_flash(_args):
    """Flash the active build with west."""
    active = load_active()
    print(f"\n  Flashing {active['app_name']} → {active['board_name']}")
    result = subprocess.run(
        ['west', 'flash', '--build-dir', DEBUG_BUILD_DIR],
        cwd=WORKSPACE,
    )
    sys.exit(result.returncode)


def cmd_info(_args):
    """Print the active configuration."""
    if not os.path.exists(ACTIVE_FILE):
        print("No active configuration — run 'Zephyr: Select App & Board' first.")
        return
    active = load_active()
    print("\nActive Zephyr configuration:")
    print(f"  Application : {active.get('app_name', '—')}")
    print(f"  App path    : {active.get('app_path', '—')}")
    print(f"  Board       : {active.get('board_name', '—')}")
    print(f"  Board ID    : {active.get('board_id', '—')}")
    print(f"  Build dir   : {active.get('build_dir', '—')}")
    print(f"  OpenOCD cfg : {active.get('openocd_cfg', '—')}")
    print(f"  SVD file    : {active.get('svd_file', '—')}")


def main():
    parser = argparse.ArgumentParser(description='Zephyr workspace manager')
    sub = parser.add_subparsers(dest='command', metavar='command')

    sub.add_parser('select', help='Interactively select app and board')

    build_p = sub.add_parser('build', help='Build the active app')
    build_p.add_argument('--pristine', '-p', action='store_true',
                         help='Clean build (west build --pristine)')

    sub.add_parser('flash', help='Flash the active build')
    sub.add_parser('info', help='Show active configuration')

    args = parser.parse_args()

    commands = {
        'select': cmd_select,
        'build': cmd_build,
        'flash': cmd_flash,
        'info': cmd_info,
    }

    fn = commands.get(args.command)
    if fn:
        fn(args)
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
