#!/usr/bin/env python3
"""Zephyr workspace manager — app/board selection, build, flash, and clean."""
import argparse
import json
import os
import shutil
import subprocess
import sys

WORKSPACE = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
CONFIG_FILE = os.path.join(WORKSPACE, '.vscode', 'zephyr-config.json')
ACTIVE_FILE = os.path.join(WORKSPACE, '.vscode', '.active-config.json')
ACTIVE_OCD_CFG = os.path.join(WORKSPACE, '.vscode', 'openocd', 'active.cfg')
ACTIVE_SVD     = os.path.join(WORKSPACE, '.vscode', 'svd', 'active.svd')
ACTIVE_ELF     = os.path.join(WORKSPACE, '.vscode', 'active.elf')


def load_config():
    if not os.path.exists(CONFIG_FILE):
        print(f"ERROR: Config file not found: {CONFIG_FILE}")
        sys.exit(1)
    with open(CONFIG_FILE) as f:
        return json.load(f)


def load_active():
    if not os.path.exists(ACTIVE_FILE):
        print("ERROR: No active configuration. Run 'Select App' and 'Select Board' first.")
        sys.exit(1)
    with open(ACTIVE_FILE) as f:
        return json.load(f)


def save_active(active):
    with open(ACTIVE_FILE, 'w') as f:
        json.dump(active, f, indent=2)


def apply_board(active, board):
    """Write board fields into active config and update side-effect files."""
    svd_rel = board.get('svd_file', '')
    svd_abs = os.path.join(WORKSPACE, svd_rel) if svd_rel else ''

    active.update({
        'board_id': board['id'],
        'board_name': board['name'],
        'openocd_cfg': board.get('openocd_cfg', ''),
        'gdb_target': board.get('gdb_target', ''),
        'svd_file': svd_rel,
        'board_root': board.get('board_root', ''),
    })

    # Write active.cfg
    board_cfg_path = os.path.join(WORKSPACE, active['openocd_cfg'])
    os.makedirs(os.path.dirname(ACTIVE_OCD_CFG), exist_ok=True)
    with open(ACTIVE_OCD_CFG, 'w') as f:
        f.write(f"# Auto-generated by zephyr.py — do not edit manually.\n")
        f.write(f"# Board: {board['name']} ({board['id']})\n")
        f.write(f"source \"{board_cfg_path}\"\n")

    # Copy SVD
    os.makedirs(os.path.dirname(ACTIVE_SVD), exist_ok=True)
    if svd_abs and os.path.exists(svd_abs):
        shutil.copy2(svd_abs, ACTIVE_SVD)
    else:
        open(ACTIVE_SVD, 'w').close()


def build_dir_for(app_path):
    """Return the build directory path for a given app path (relative to workspace)."""
    return os.path.join(WORKSPACE, app_path, 'build')


def update_active_elf(app_path):
    """Point .vscode/active.elf at the current app's zephyr.elf."""
    elf = os.path.join(build_dir_for(app_path), 'zephyr', 'zephyr.elf')
    # Remove existing symlink or file
    if os.path.lexists(ACTIVE_ELF):
        os.remove(ACTIVE_ELF)
    os.symlink(elf, ACTIVE_ELF)


def cmd_set_board(args):
    """Set the active board by ID."""
    config = load_config()
    board_id = args.board_id

    board = next((b for b in config.get('boards', []) if b['id'] == board_id), None)
    if board is None:
        print(f"ERROR: Unknown board '{board_id}'")
        print("Known boards:", ', '.join(b['id'] for b in config.get('boards', [])))
        sys.exit(1)

    # Load or create active config
    active = {}
    if os.path.exists(ACTIVE_FILE):
        with open(ACTIVE_FILE) as f:
            active = json.load(f)

    apply_board(active, board)
    save_active(active)

    print(f"Board set: {board['name']} ({board_id})")


def cmd_set_app(args):
    """Set the active application by path."""
    app_path = args.app_path

    # Load or create active config
    active = {}
    if os.path.exists(ACTIVE_FILE):
        with open(ACTIVE_FILE) as f:
            active = json.load(f)

    active['app_path'] = app_path

    save_active(active)
    update_active_elf(app_path)
    print(f"App set: {app_path}")


def cmd_build(args):
    """Build the active Zephyr application with west."""
    active = load_active()
    app_path = active.get('app_path')
    board_id = active.get('board_id')

    if not app_path:
        print("ERROR: No app selected. Run 'Zephyr: Select App' first.")
        sys.exit(1)
    if not board_id:
        print("ERROR: No board selected. Run 'Zephyr: Select Board' first.")
        sys.exit(1)

    app_abs = os.path.join(WORKSPACE, app_path)
    build_dir = build_dir_for(app_path)

    print(f"  App   : {app_path}")
    print(f"  Board : {board_id}")
    print(f"  Build : {os.path.relpath(build_dir, WORKSPACE)}")
    print()

    cmd = [
        'west', 'build',
        '-b', board_id,
        app_abs,
        '--build-dir', build_dir,
    ]
    if args.pristine:
        cmd.append('--pristine')

    board_root = active.get('board_root', '')
    if board_root:
        board_root_abs = os.path.join(WORKSPACE, board_root)
        cmd.extend(['--', f'-DBOARD_ROOT={board_root_abs}'])

    result = subprocess.run(cmd, cwd=WORKSPACE)
    if result.returncode == 0:
        update_active_elf(app_path)
    sys.exit(result.returncode)


def cmd_clean(args):
    """Delete the build directory for the active app."""
    active = load_active()
    app_path = active.get('app_path')

    if not app_path:
        print("ERROR: No app selected. Run 'Zephyr: Select App' first.")
        sys.exit(1)

    build_dir = build_dir_for(app_path)

    if os.path.exists(build_dir):
        shutil.rmtree(build_dir)
        print(f"Cleaned: {os.path.relpath(build_dir, WORKSPACE)}")
    else:
        print(f"Nothing to clean: {os.path.relpath(build_dir, WORKSPACE)}")


def cmd_flash(_args):
    """Flash the active build with west."""
    active = load_active()
    app_path = active.get('app_path', '')
    build_dir = build_dir_for(app_path)

    print(f"  Flashing {app_path} → {active.get('board_id', '?')}")
    result = subprocess.run(
        ['west', 'flash', '--build-dir', build_dir],
        cwd=WORKSPACE,
    )
    sys.exit(result.returncode)


def cmd_info(_args):
    """Print the active configuration."""
    if not os.path.exists(ACTIVE_FILE):
        print("No active configuration — run 'Select App' and 'Select Board' first.")
        return
    active = load_active()
    app_path = active.get('app_path', '—')
    print("\nActive Zephyr configuration:")
    print(f"  App path    : {app_path}")
    print(f"  Board       : {active.get('board_id', '—')}")
    print(f"  Build dir   : {os.path.relpath(build_dir_for(app_path), WORKSPACE) if app_path != '—' else '—'}")
    print(f"  OpenOCD cfg : {active.get('openocd_cfg', '—')}")
    print(f"  SVD file    : {active.get('svd_file', '—')}")


def main():
    parser = argparse.ArgumentParser(description='Zephyr workspace manager')
    sub = parser.add_subparsers(dest='command', metavar='command')

    sb = sub.add_parser('set-board', help='Set the active board')
    sb.add_argument('board_id', help='Board ID (e.g. tracker/stm32u575xx)')

    sa = sub.add_parser('set-app', help='Set the active application')
    sa.add_argument('app_path', help='App path relative to workspace (e.g. project/samples/gps)')

    build_p = sub.add_parser('build', help='Build the active app')
    build_p.add_argument('--pristine', '-p', action='store_true',
                         help='Clean build (west build --pristine)')

    sub.add_parser('clean', help='Delete the build directory for the active app')
    sub.add_parser('flash', help='Flash the active build')
    sub.add_parser('info', help='Show active configuration')

    args = parser.parse_args()

    commands = {
        'set-board': cmd_set_board,
        'set-app':   cmd_set_app,
        'build':     cmd_build,
        'clean':     cmd_clean,
        'flash':     cmd_flash,
        'info':      cmd_info,
    }

    fn = commands.get(args.command)
    if fn:
        fn(args)
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
