# Console over USB CDC ACM
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Tracker Display"
CONFIG_USB_DEVICE_VID=0x2FE3
CONFIG_USB_DEVICE_PID=0x0003

# Display
CONFIG_DISPLAY=y
CONFIG_SPI=y
CONFIG_GPIO=y

# Display UI library (Sharp LS027B7DH01A defaults)
CONFIG_DISPLAY_UI=y
CONFIG_DISPLAY_UI_FB_W=400
CONFIG_DISPLAY_UI_FB_H=240
CONFIG_DISPLAY_UI_PORTRAIT=y
CONFIG_DISPLAY_UI_ROWS=3


# Power domains (3V3 + 5V rails)
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_POWER_DOMAIN=y
CONFIG_TIMEOUT_64BIT=y
CONFIG_POWER_DOMAIN=y
CONFIG_POWER_DOMAIN_GPIO_INIT_PRIORITY=1
